apiVersion: apps/v1
kind: Deployment
metadata:
  name: mgkcloud-helm01-deployment
spec:
  selector:
    matchLabels:
      app: mgkcloud-helm01-pod
  template:
    metadata:
      labels:
        app: mgkcloud-helm01-pod
    spec:
      containers:
      - name: mgkcloud-helm01-container
        image: barclaysacr02.azurecr.io/mgkcloud-helm01:latest
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 5000